version: '3.1'

services:
  jupyterlab:
    container_name: jupyterlab
    restart: always
    user: root
    build: .
    image: utfpr/jupyterlab:latest
    working_dir: /opt/urbs-data-analysis/
    ports:
      - 8085:8085
      - 4040:4040
    volumes:
      - .:/opt/urbs-data-analysis/
      - /work/datalake:/data/